apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-scm
  labels:
    app: backend-scm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-scm
  template:
    metadata:
      labels:
        app: backend-scm
    spec:
      containers:
      - name: backend-scm
        image: fcamparasilva/backend-scm:alpha
        ports:
        - containerPort: 3030
        env:
        - name: NODE_ENV
          value: "staging"
        - name: GITHUB_CLIENT_ID
          value: "e50ff23474ac9ae0a87a"
        - name: GITHUB_CLIENT_SECRET
          value: "0ab3cbde9601aafd574e13a8971f934755ae1d1d"
        - name: SECRET_OR_KEY
          value: "b00tc4mp18"