version: '3'
services:
  scm:
    image: "fcamparasilva/backend-scm:alpha"
    ports:
      - "3030:3030"
  user:
    image: "fcamparasilva/backend-user:alpha"
    ports:
      - "3020:3020"
  frontned:
    image: "fcamparasilva/frontend:alpha"
    ports:
      - "80:80"