apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend-scm.fullname" . }}
  labels:
{{ include "backend-scm.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      nodePort: {{ .Values.service.nodePort }}
      name: http
  selector:
    app.kubernetes.io/name: {{ include "backend-scm.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
